name: Make more memory available
description: Stops services and adds swap

inputs:
  max:
    description: Maximum memory to suggest using
    default: 50000

outputs:
  available:
    description: Available memory
    value: ${{ steps.memory.outputs.available }}
  suggested:
    description: Memory suggested for use (constrained by max and available)
    value: ${{ steps.memory.outputs.suggested }}

runs:
  using: composite
  steps:
    - name: Stop services
      shell: bash
      run: |
        sudo systemctl disable php8.1-fpm mono-xsp4 walinuxagent multipathd walinuxagent chrony cron getty@tty1 networkd-dispatcher rsyslog serial-getty@ttyS0 snapd multipathd.socket snapd.socket
        sudo systemctl stop php8.1-fpm mono-xsp4 walinuxagent multipathd walinuxagent chrony cron getty@tty1 networkd-dispatcher rsyslog serial-getty@ttyS0 snapd
        sudo killall mono

    - name: enable swap
      shell: bash
      run: |
        sudo fallocate -l 10G /mnt/big-swapfile
        sudo chmod 600 /mnt/big-swapfile
        sudo mkswap /mnt/big-swapfile
        sudo swapon /mnt/big-swapfile

    - name: Report Free
      id: memory
      shell: bash
      env:
        max: ${{ inputs.max }}
      run: |
        free | perl -ne 'next unless /Mem:.*\s(\d+)$/; my $m=$1; $m/=102400; $m=int($m)*100; my $max = $ENV{max} || $m; my $s = ($m < $max ? $m : $max); print "suggested=$s\n"."available=$m\n"' >> "$GITHUB_OUTPUT"
