name: "C#: Run QL Tests"

on:
  push:

defaults:
  run:
    working-directory: csharp

permissions:
  contents: read

jobs:
  qltest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        slice: ["1/2", "2/2"]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: ./csharp/actions/create-extractor-pack
      - name: Cache compilation cache
        id: query-cache
        uses: ./.github/actions/cache-query-compilation
        with:
          key: csharp-qltest-${{ matrix.slice }}
      - name: Run QL tests
        run: |
          codeql test run --threads=0 --ram 50000 --slice ${{ matrix.slice }} --search-path extractor-pack --check-databases --check-undefined-labels --check-repeated-labels --check-redefined-labels --consistency-queries ql/consistency-queries ql/test --compilation-cache "${{ steps.query-cache.outputs.cache-dir }}"
        env:
          GITHUB_TOKEN: ${{ github.token }}
